<<<<<<< HEAD
# Generated by Django 3.2.16 on 2023-01-17 01:26
=======
# Generated by Django 3.2.16 on 2023-01-16 11:26
>>>>>>> a88faa461f0e1cc1829e8ebe1d98a6b6839ec192

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Endereço completo'),
        ),
    ]
