# Generated by Django 3.2.9 on 2023-01-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='Data de Emissão'),
        ),
    ]
