# Generated by Django 3.2.9 on 2023-01-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_notas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='data',
            field=models.DateField(null=True, verbose_name='Data de Emissão'),
        ),
    ]
