# Generated by Django 3.2.16 on 2023-01-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_notas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
